/**
 * Données de démonstration réalistes pour la présentation
 * Restaurant: "Le Petit Bistrot" - Restaurant gastronomique parisien
 */

// Génère une date relative au jour actuel
const daysAgo = (days: number, hours = 0, minutes = 0) => {
  const date = new Date();
  date.setDate(date.getDate() - days);
  date.setHours(hours, minutes, 0, 0);
  return date.toISOString();
};

const hoursAgo = (hours: number) => {
  const date = new Date();
  date.setHours(date.getHours() - hours);
  return date.toISOString();
};

// ========== APPELS / CALLS ==========
export const demoCalls = [
  {
    id: "call-001",
    phoneNumber: "+33 6 12 34 56 78",
    callerName: "Marie Dupont",
    startTime: hoursAgo(1),
    endTime: hoursAgo(0.9),
    duration: 180,
    status: "completed",
    eventType: "reservation",
    appointmentDate: daysAgo(-2, 20, 0), // Dans 2 jours
    numberOfGuests: 4,
    summary: "Réservation pour 4 personnes samedi soir à 20h. Table en terrasse demandée si possible. Menu dégustation pour une occasion spéciale (anniversaire).",
    transcript: "Client: Bonjour, je souhaite réserver une table pour samedi soir.\nIA: Bonjour ! Avec plaisir. Pour combien de personnes ?\nClient: Nous serons 4.\nIA: Parfait. À quelle heure souhaitez-vous venir ?\nClient: 20h si possible, et si vous avez une table en terrasse ce serait idéal.\nIA: Je vous réserve une table pour 4 à 20h. Je note la préférence terrasse. Puis-je avoir votre nom ?\nClient: Marie Dupont.\nIA: C'est noté Madame Dupont. Y a-t-il une occasion particulière ?\nClient: Oui, c'est l'anniversaire de mon mari.\nIA: Parfait, je le note. Votre réservation est confirmée pour samedi 20h, 4 personnes. À bientôt !",
    aiConfidenceScore: 95,
    sentimentScore: 0.9,
    keyTopics: ["réservation", "anniversaire", "terrasse", "menu dégustation"],
  },
  {
    id: "call-002",
    phoneNumber: "+33 6 98 76 54 32",
    callerName: "Pierre Martin",
    startTime: hoursAgo(3),
    endTime: hoursAgo(2.95),
    duration: 120,
    status: "completed",
    eventType: "reservation",
    appointmentDate: daysAgo(-1, 12, 30),
    numberOfGuests: 2,
    summary: "Déjeuner d'affaires pour 2 personnes demain midi. Table calme demandée pour discussion importante.",
    transcript: "Client: Bonjour, j'aurais besoin d'une table pour un déjeuner d'affaires demain.\nIA: Bonjour Monsieur. Pour combien de personnes ?\nClient: 2 personnes, vers 12h30.\nIA: Très bien. Souhaitez-vous une table particulière ?\nClient: Oui, quelque chose de calme si possible, on doit discuter affaires.\nIA: Je vous réserve une table au fond de la salle, plus tranquille. Votre nom ?\nClient: Pierre Martin.\nIA: Parfait M. Martin, c'est confirmé pour demain 12h30, 2 personnes, table calme. Bonne journée !",
    aiConfidenceScore: 92,
    sentimentScore: 0.75,
    keyTopics: ["déjeuner affaires", "table calme", "professionnel"],
  },
  {
    id: "call-003",
    phoneNumber: "+33 7 45 67 89 01",
    callerName: "Sophie Bernard",
    startTime: hoursAgo(5),
    endTime: hoursAgo(4.97),
    duration: 90,
    status: "completed",
    eventType: "information",
    summary: "Demande d'informations sur les menus végétariens et les allergies. La cliente reviendra pour réserver.",
    transcript: "Client: Bonjour, je voudrais savoir si vous proposez des options végétariennes ?\nIA: Bonjour ! Oui, absolument. Nous avons plusieurs plats végétariens et notre chef peut adapter la plupart des plats.\nClient: Super, et pour les allergies aux noix ?\nIA: Nous prenons les allergies très au sérieux. Il suffit de le signaler lors de la réservation et notre chef adaptera les plats.\nClient: Parfait, je vous rappellerai pour réserver.\nIA: Avec plaisir ! N'hésitez pas si vous avez d'autres questions. Bonne journée !",
    aiConfidenceScore: 88,
    sentimentScore: 0.8,
    keyTopics: ["végétarien", "allergies", "informations"],
  },
  {
    id: "call-004",
    phoneNumber: "+33 6 23 45 67 89",
    callerName: "Jean-Luc Moreau",
    startTime: daysAgo(1, 18, 30),
    endTime: daysAgo(1, 18, 33),
    duration: 150,
    status: "completed",
    eventType: "reservation",
    appointmentDate: daysAgo(0, 19, 30),
    numberOfGuests: 6,
    summary: "Réservation groupe pour 6 personnes ce soir. Demande de menu pré-commandé pour gagner du temps.",
    transcript: "Client: Bonsoir, on aimerait réserver pour ce soir, on est 6.\nIA: Bonsoir ! Je vérifie nos disponibilités... Oui, j'ai de la place à 19h30, ça vous conviendrait ?\nClient: Parfait ! On est un peu pressés, on a un spectacle après.\nIA: Je comprends. Nous pouvons préparer un menu en avance si vous le souhaitez.\nClient: Ah oui, ce serait super !\nIA: Je vous envoie notre carte par SMS, vous pourrez pré-commander. Votre nom ?\nClient: Jean-Luc Moreau.\nIA: C'est noté ! À ce soir 19h30 pour 6 personnes.",
    aiConfidenceScore: 91,
    sentimentScore: 0.85,
    keyTopics: ["groupe", "pré-commande", "spectacle", "service rapide"],
  },
  {
    id: "call-005",
    phoneNumber: "+33 6 11 22 33 44",
    callerName: "Client anonyme",
    startTime: daysAgo(1, 14, 15),
    endTime: daysAgo(1, 14, 16),
    duration: 45,
    status: "no_answer",
    summary: "Appel sans réponse du client après le message d'accueil.",
    aiConfidenceScore: 0,
    sentimentScore: null,
    keyTopics: [],
  },
  {
    id: "call-006",
    phoneNumber: "+33 7 88 99 00 11",
    callerName: "Isabelle Leroy",
    startTime: daysAgo(2, 11, 0),
    endTime: daysAgo(2, 11, 4),
    duration: 210,
    status: "completed",
    eventType: "reservation",
    appointmentDate: daysAgo(-7, 20, 0),
    numberOfGuests: 8,
    summary: "Grande tablée pour 8 personnes dans une semaine. Célébration de fiançailles. Menu dégustation avec accord mets-vins demandé.",
    transcript: "Client: Bonjour, je prépare une surprise pour des fiançailles, on serait 8 personnes.\nIA: Félicitations ! C'est une belle occasion. Quand souhaiteriez-vous venir ?\nClient: Dans une semaine, le samedi soir.\nIA: Parfait, j'ai de la place. Souhaitez-vous quelque chose de spécial ?\nClient: Oui, le menu dégustation avec accord vins si possible.\nIA: Excellent choix ! Je note aussi pour les fiançailles, nous pouvons prévoir un dessert spécial.\nClient: Oh ce serait adorable ! Merci beaucoup.\nIA: Votre nom ?\nClient: Isabelle Leroy.\nIA: C'est noté Mme Leroy, 8 personnes le samedi 20h, menu dégustation avec vins, surprise fiançailles. Bravo encore !",
    aiConfidenceScore: 97,
    sentimentScore: 0.95,
    keyTopics: ["fiançailles", "grande tablée", "menu dégustation", "accord vins", "surprise"],
  },
  {
    id: "call-007",
    phoneNumber: "+33 6 55 44 33 22",
    callerName: "François Petit",
    startTime: daysAgo(2, 19, 45),
    endTime: daysAgo(2, 19, 47),
    duration: 100,
    status: "canceled",
    eventType: "cancellation",
    summary: "Annulation de réservation pour raison personnelle. Client poli, souhaite reporter ultérieurement.",
    transcript: "Client: Bonsoir, je dois malheureusement annuler ma réservation de demain.\nIA: Bonsoir Monsieur. Je suis désolée d'apprendre cela. Pouvez-vous me donner votre nom ?\nClient: François Petit, j'avais réservé pour 4 à 20h.\nIA: Je retrouve votre réservation. C'est bien annulé. Souhaitez-vous reporter ?\nClient: Pas pour le moment, je vous rappellerai.\nIA: Très bien. Nous espérons vous revoir bientôt. Bonne soirée !",
    aiConfidenceScore: 85,
    sentimentScore: 0.5,
    keyTopics: ["annulation", "report"],
  },
  {
    id: "call-008",
    phoneNumber: "+33 6 77 88 99 00",
    callerName: "Thomas Garnier",
    startTime: daysAgo(3, 12, 30),
    endTime: daysAgo(3, 12, 32),
    duration: 95,
    status: "completed",
    eventType: "reservation",
    appointmentDate: daysAgo(1, 13, 0),
    numberOfGuests: 3,
    summary: "Déjeuner en famille pour 3 personnes. Chaise haute nécessaire pour enfant.",
    aiConfidenceScore: 90,
    sentimentScore: 0.82,
    keyTopics: ["famille", "enfant", "chaise haute"],
  },
  {
    id: "call-009",
    phoneNumber: "+33 7 12 34 56 78",
    callerName: "Catherine Blanc",
    startTime: daysAgo(3, 17, 0),
    endTime: daysAgo(3, 17, 3),
    duration: 160,
    status: "completed",
    eventType: "reservation",
    appointmentDate: daysAgo(0, 20, 30),
    numberOfGuests: 2,
    summary: "Dîner romantique pour 2 personnes ce soir. Table avec vue demandée si possible.",
    aiConfidenceScore: 93,
    sentimentScore: 0.88,
    keyTopics: ["romantique", "vue", "dîner"],
  },
  {
    id: "call-010",
    phoneNumber: "+33 6 00 11 22 33",
    callerName: "Michel Roux",
    startTime: daysAgo(4, 10, 15),
    endTime: daysAgo(4, 10, 17),
    duration: 110,
    status: "completed",
    eventType: "reservation",
    appointmentDate: daysAgo(2, 12, 0),
    numberOfGuests: 5,
    summary: "Déjeuner entre collègues pour 5 personnes. Menus du jour demandés.",
    aiConfidenceScore: 88,
    sentimentScore: 0.75,
    keyTopics: ["collègues", "menu du jour", "déjeuner"],
  },
];

// ========== STATISTIQUES DASHBOARD ==========
export const demoStats = {
  totalCalls: 127,
  callsVariation: 12.5,
  conversionRate: 78.4,
  conversionVariation: 5.2,
  avgDuration: 142, // secondes
  durationVariation: -3.1,
  reminders: 8,
  remindersVariation: 15.0,
  convertedClients: 99,
  convertedClientsVariation: 8.7,
  appointmentsTaken: 89,
  appointmentsVariation: 10.3,
};

export const demoChartData = [
  { date: daysAgo(6), calls: 15, conversions: 12 },
  { date: daysAgo(5), calls: 18, conversions: 14 },
  { date: daysAgo(4), calls: 22, conversions: 18 },
  { date: daysAgo(3), calls: 19, conversions: 15 },
  { date: daysAgo(2), calls: 25, conversions: 20 },
  { date: daysAgo(1), calls: 21, conversions: 16 },
  { date: daysAgo(0), calls: 7, conversions: 4 },
];

export const demoAIInsights = [
  {
    title: "Pic d'appels le samedi",
    description: "35% de vos réservations sont prises le samedi entre 10h et 12h. Assurez-vous d'avoir une couverture optimale.",
    icon: "chart",
    type: "opportunity",
    priority: "high",
  },
  {
    title: "Taux de conversion excellent",
    description: "Votre taux de 78.4% est 15% supérieur à la moyenne du secteur restauration.",
    icon: "trending-up",
    type: "positive",
    priority: "medium",
  },
  {
    title: "Créneaux du soir populaires",
    description: "Les réservations entre 19h30 et 21h représentent 60% de votre activité. Pensez à ouvrir un second service.",
    icon: "clock",
    type: "insight",
    priority: "medium",
  },
];

// ========== AVIS / REVIEWS ==========
export const demoReviews = [
  {
    id: "rev-001",
    platform: "google",
    reviewerName: "Marie L.",
    reviewerAvatarUrl: null,
    rating: 5,
    content: "Une expérience culinaire exceptionnelle ! Le menu dégustation était un véritable voyage gastronomique. Le service était impeccable, discret mais attentif. Le cadre est magnifique, parfait pour une soirée romantique. Je recommande vivement !",
    reviewDate: daysAgo(1),
    isRead: true,
    responseStatus: "published",
    responseText: "Merci infiniment Marie pour ce magnifique retour ! Nous sommes ravis que notre menu dégustation vous ait transportée. Au plaisir de vous revoir très bientôt !",
    sentiment: "very_positive",
    aiSummary: "Expérience très positive : qualité gastronomique, service excellent, ambiance romantique.",
  },
  {
    id: "rev-002",
    platform: "tripadvisor",
    reviewerName: "Pierre D.",
    reviewerAvatarUrl: null,
    rating: 4,
    content: "Très bon restaurant dans l'ensemble. Les plats étaient délicieux et bien présentés. Petit bémol sur l'attente entre les plats qui était un peu longue. Mais le dessert valait l'attente !",
    reviewDate: daysAgo(3),
    isRead: true,
    responseStatus: "published",
    responseText: "Merci Pierre pour votre avis constructif. Nous prenons note du temps d'attente et travaillons à l'améliorer. Heureux que le dessert ait été à la hauteur !",
    sentiment: "positive",
    aiSummary: "Globalement satisfait, critique mineure sur le temps d'attente entre les plats.",
  },
  {
    id: "rev-003",
    platform: "google",
    reviewerName: "Sophie M.",
    reviewerAvatarUrl: null,
    rating: 5,
    content: "Le brunch du dimanche est une pure merveille ! Produits frais, fait maison, et un accueil chaleureux. Les enfants ont adoré. On reviendra !",
    reviewDate: daysAgo(5),
    isRead: true,
    responseStatus: "published",
    responseText: "Merci Sophie ! Notre brunch est préparé avec amour chaque dimanche. Nous serons ravis d'accueillir à nouveau toute la famille !",
    sentiment: "very_positive",
    aiSummary: "Excellente expérience brunch, adapté aux familles avec enfants.",
  },
  {
    id: "rev-004",
    platform: "facebook",
    reviewerName: "Laurent B.",
    reviewerAvatarUrl: null,
    rating: 3,
    content: "Cuisine correcte mais les portions sont un peu petites pour le prix. Le cadre est agréable mais bruyant le soir du vendredi.",
    reviewDate: daysAgo(7),
    isRead: true,
    responseStatus: "draft",
    responseText: "",
    sentiment: "neutral",
    aiSummary: "Feedback mitigé : portions jugées petites, ambiance bruyante le vendredi soir.",
    isFlagged: true,
  },
  {
    id: "rev-005",
    platform: "google",
    reviewerName: "Isabelle F.",
    reviewerAvatarUrl: null,
    rating: 5,
    content: "Nous avons fêté nos fiançailles ici et c'était parfait ! L'équipe avait préparé une surprise avec un dessert personnalisé. Moment inoubliable !",
    reviewDate: daysAgo(8),
    isRead: false,
    responseStatus: "none",
    sentiment: "very_positive",
    aiSummary: "Célébration de fiançailles réussie, surprise dessert appréciée.",
  },
  {
    id: "rev-006",
    platform: "tripadvisor",
    reviewerName: "Antoine R.",
    reviewerAvatarUrl: null,
    rating: 4,
    content: "Excellent rapport qualité-prix pour le menu du jour. Produits de saison bien cuisinés. Service efficace pour un déjeuner d'affaires.",
    reviewDate: daysAgo(10),
    isRead: true,
    responseStatus: "published",
    responseText: "Merci Antoine ! Notre menu du jour change chaque semaine pour offrir le meilleur de la saison. À très bientôt !",
    sentiment: "positive",
    aiSummary: "Bon rapport qualité-prix, adapté aux déjeuners professionnels.",
  },
  {
    id: "rev-007",
    platform: "google",
    reviewerName: "Nathalie C.",
    reviewerAvatarUrl: null,
    rating: 5,
    content: "Chef extraordinaire ! J'ai des allergies alimentaires et ils ont adapté tout le menu pour moi sans jamais me faire sentir différente. Rare et précieux.",
    reviewDate: daysAgo(12),
    isRead: false,
    responseStatus: "none",
    sentiment: "very_positive",
    aiSummary: "Excellente gestion des allergies alimentaires, service personnalisé.",
  },
  {
    id: "rev-008",
    platform: "yelp",
    reviewerName: "Marc V.",
    reviewerAvatarUrl: null,
    rating: 2,
    content: "Déçu par ma dernière visite. Réservation non honorée à l'heure, attente 30 min au bar. Le repas était bon mais l'expérience gâchée.",
    reviewDate: daysAgo(14),
    isRead: true,
    responseStatus: "published",
    responseText: "Marc, nous sommes sincèrement désolés pour cette expérience. Nous avons renforcé notre organisation pour éviter ces retards. Permettez-nous de vous inviter pour rectifier cela.",
    sentiment: "negative",
    aiSummary: "Problème de gestion des réservations, attente excessive malgré la qualité du repas.",
    isFlagged: true,
  },
];

export const demoReviewStats = {
  globalScore: 4.6,
  totalReviews: 284,
  newReviewsPeriod: 23,
  responseRate: 87,
  unansweredReviews: 8,
  clickThroughRate: 12.4,
  clickThroughRateDataAvailable: true,
  clickThroughRateVariation: 2.1,
  avgResponseTimeHours: 4.5,
  platforms: {
    google: { score: 4.7, count: 156 },
    tripadvisor: { score: 4.5, count: 78 },
    facebook: { score: 4.4, count: 35 },
    yelp: { score: 4.3, count: 15 },
  },
  ratingDistribution: {
    5: 168,
    4: 82,
    3: 24,
    2: 7,
    1: 3,
  },
  sentimentDistribution: {
    very_positive: 145,
    positive: 95,
    neutral: 32,
    negative: 10,
    very_negative: 2,
  },
  trends: [
    { date: daysAgo(6), count: 4, avgRating: 4.8 },
    { date: daysAgo(5), count: 3, avgRating: 4.3 },
    { date: daysAgo(4), count: 5, avgRating: 4.6 },
    { date: daysAgo(3), count: 2, avgRating: 5.0 },
    { date: daysAgo(2), count: 4, avgRating: 4.5 },
    { date: daysAgo(1), count: 3, avgRating: 4.7 },
    { date: daysAgo(0), count: 2, avgRating: 4.5 },
  ],
  platformComparison: [
    { platform: "Google", score: 4.7, count: 156, trend: 0.1 },
    { platform: "TripAdvisor", score: 4.5, count: 78, trend: 0.2 },
    { platform: "Facebook", score: 4.4, count: 35, trend: -0.1 },
    { platform: "Yelp", score: 4.3, count: 15, trend: 0.0 },
  ],
  sentimentTrend: [
    { date: daysAgo(6), positive: 80, neutral: 15, negative: 5 },
    { date: daysAgo(5), positive: 75, neutral: 20, negative: 5 },
    { date: daysAgo(4), positive: 85, neutral: 10, negative: 5 },
    { date: daysAgo(3), positive: 90, neutral: 8, negative: 2 },
    { date: daysAgo(2), positive: 82, neutral: 12, negative: 6 },
    { date: daysAgo(1), positive: 88, neutral: 10, negative: 2 },
    { date: daysAgo(0), positive: 85, neutral: 12, negative: 3 },
  ],
};

// ========== MARKETING ==========
export const demoMarketingStats = {
  totalContacts: 1847,
  newContactsPeriod: 124,
  totalCampaigns: 12,
  campaignsSentPeriod: 3,
  totalEmailsSent: 4523,
  avgOpenRate: 42.8,
  avgClickRate: 8.6,
  totalRevenue: 12450,
  costPerConversion: 2.3,
};

export const demoMarketingChartData = [
  { date: daysAgo(6), emailsSent: 320, opened: 142, clicked: 28 },
  { date: daysAgo(5), emailsSent: 0, opened: 0, clicked: 0 },
  { date: daysAgo(4), emailsSent: 450, opened: 198, clicked: 42 },
  { date: daysAgo(3), emailsSent: 0, opened: 0, clicked: 0 },
  { date: daysAgo(2), emailsSent: 280, opened: 118, clicked: 22 },
  { date: daysAgo(1), emailsSent: 0, opened: 0, clicked: 0 },
  { date: daysAgo(0), emailsSent: 180, opened: 72, clicked: 15 },
];

export const demoMarketingContacts = [
  { id: "mc-001", firstName: "Marie", lastName: "Dupont", email: "marie.dupont@email.com", phone: "+33612345678", source: "reservation", optInEmail: true, optInSms: true, tags: ["vip", "anniversaire"], createdAt: daysAgo(45) },
  { id: "mc-002", firstName: "Pierre", lastName: "Martin", email: "p.martin@business.fr", phone: "+33698765432", source: "website", optInEmail: true, optInSms: false, tags: ["business"], createdAt: daysAgo(30) },
  { id: "mc-003", firstName: "Sophie", lastName: "Bernard", email: "sophie.b@gmail.com", phone: "+33745678901", source: "review", optInEmail: true, optInSms: true, tags: ["fidèle"], createdAt: daysAgo(60) },
  { id: "mc-004", firstName: "Jean", lastName: "Moreau", email: "jean.moreau@orange.fr", phone: "+33623456789", source: "reservation", optInEmail: true, optInSms: true, tags: ["groupe"], createdAt: daysAgo(15) },
  { id: "mc-005", firstName: "Isabelle", lastName: "Leroy", email: "isabelle.leroy@yahoo.fr", phone: "+33788990011", source: "reservation", optInEmail: true, optInSms: true, tags: ["vip", "fiançailles"], createdAt: daysAgo(8) },
];

export const demoMarketingCampaigns = [
  { id: "camp-001", name: "Menu de Noël 2024", type: "email", status: "sent", sentAt: daysAgo(5), recipientCount: 1245, openRate: 48.2, clickRate: 12.5 },
  { id: "camp-002", name: "Brunch Spécial Dimanche", type: "sms", status: "sent", sentAt: daysAgo(12), recipientCount: 890, openRate: null, clickRate: 15.8 },
  { id: "camp-003", name: "Offre Fidélité -20%", type: "email", status: "scheduled", scheduledFor: daysAgo(-3), recipientCount: 650 },
  { id: "camp-004", name: "Saint-Valentin 2025", type: "email", status: "draft", recipientCount: 0 },
];

// ========== GARANTIE CB / PROTECTION ==========
export const demoGuaranteeSessions = [
  {
    id: "gs-001",
    customerName: "Marie Dupont",
    customerEmail: "marie.dupont@email.com",
    customerPhone: "+33612345678",
    numberOfGuests: 4,
    reservationDate: daysAgo(-2),
    reservationTime: "20:00",
    status: "validated",
    penaltyAmount: 30,
    reminderCount: 0,
    createdAt: daysAgo(3),
    cardValidatedAt: daysAgo(2),
  },
  {
    id: "gs-002",
    customerName: "Pierre Martin",
    customerEmail: "p.martin@business.fr",
    customerPhone: "+33698765432",
    numberOfGuests: 2,
    reservationDate: daysAgo(-1),
    reservationTime: "12:30",
    status: "validated",
    penaltyAmount: 25,
    reminderCount: 0,
    createdAt: daysAgo(2),
    cardValidatedAt: daysAgo(1),
  },
  {
    id: "gs-003",
    customerName: "Jean-Luc Moreau",
    customerEmail: "jl.moreau@gmail.com",
    customerPhone: "+33623456789",
    numberOfGuests: 6,
    reservationDate: daysAgo(0),
    reservationTime: "19:30",
    status: "pending",
    penaltyAmount: 35,
    reminderCount: 1,
    createdAt: daysAgo(1),
  },
  {
    id: "gs-004",
    customerName: "Sophie Blanc",
    customerEmail: "s.blanc@outlook.com",
    customerPhone: "+33756789012",
    numberOfGuests: 3,
    reservationDate: daysAgo(0),
    reservationTime: "20:30",
    status: "validated",
    penaltyAmount: 25,
    reminderCount: 0,
    createdAt: daysAgo(2),
    cardValidatedAt: daysAgo(1),
  },
];

export const demoNoShows = [
  {
    id: "ns-001",
    customerName: "François Petit",
    customerPhone: "+33655443322",
    numberOfGuests: 4,
    reservationDate: daysAgo(5),
    penaltyAmount: 120,
    chargeStatus: "succeeded",
    chargedAt: daysAgo(4),
  },
  {
    id: "ns-002",
    customerName: "Laurent Noir",
    customerPhone: "+33611223344",
    numberOfGuests: 2,
    reservationDate: daysAgo(12),
    penaltyAmount: 50,
    chargeStatus: "succeeded",
    chargedAt: daysAgo(11),
  },
  {
    id: "ns-003",
    customerName: "Client Inconnu",
    customerPhone: "+33699887766",
    numberOfGuests: 5,
    reservationDate: daysAgo(18),
    penaltyAmount: 175,
    chargeStatus: "failed",
    failureReason: "Carte expirée",
  },
];

export const demoGuaranteeStats = {
  pendingCount: 2,
  validatedCount: 15,
  todayCount: 4,
  validationRate: 94.2,
  noShowRate: 3.8,
  recoveredAmount: 1245,
  totalNoShows: 8,
};

// ========== INTEGRATIONS ==========
export const demoIntegrations = [
  {
    id: "int-001",
    provider: "hubspot",
    status: "connected",
    lastSync: hoursAgo(2),
    syncStatus: "success",
    recordsSynced: 1847,
    connectedAt: daysAgo(30),
  },
  {
    id: "int-002",
    provider: "stripe",
    status: "connected",
    lastSync: hoursAgo(1),
    syncStatus: "success",
    recordsSynced: 523,
    connectedAt: daysAgo(45),
  },
  {
    id: "int-003",
    provider: "google_calendar",
    status: "pending",
    lastSync: null,
    syncStatus: null,
    recordsSynced: 0,
    connectedAt: null,
  },
];

// ========== RAPPORTS ==========
export const demoReports = [
  {
    id: "rep-001",
    month: "Novembre 2024",
    generatedAt: daysAgo(5),
    fileName: "rapport-novembre-2024.pdf",
    status: "generated",
  },
  {
    id: "rep-002",
    month: "Octobre 2024",
    generatedAt: daysAgo(35),
    fileName: "rapport-octobre-2024.pdf",
    status: "generated",
  },
  {
    id: "rep-003",
    month: "Septembre 2024",
    generatedAt: daysAgo(65),
    fileName: "rapport-septembre-2024.pdf",
    status: "generated",
  },
];

// ========== WAITLIST ==========
export const demoWaitlistEntries = [
  {
    id: "wl-001",
    customerName: "Thomas Garnier",
    customerPhone: "+33677889900",
    requestedDate: daysAgo(-1),
    requestedTime: "20:00",
    partySize: 4,
    status: "waiting",
    priority: 1,
    createdAt: daysAgo(2),
  },
  {
    id: "wl-002",
    customerName: "Céline Martin",
    customerPhone: "+33612987654",
    requestedDate: daysAgo(-1),
    requestedTime: "20:30",
    partySize: 2,
    status: "notified",
    priority: 2,
    createdAt: daysAgo(3),
    notifiedAt: hoursAgo(4),
  },
  {
    id: "wl-003",
    customerName: "Marc Dubois",
    customerPhone: "+33698123456",
    requestedDate: daysAgo(-3),
    requestedTime: "19:30",
    partySize: 6,
    status: "waiting",
    priority: 1,
    createdAt: daysAgo(5),
  },
];

// ========== RECOMMENDATIONS PAGE ==========
export const demoRecommendations = [
  {
    id: "rec-001",
    category: "performance",
    title: "Optimiser les créneaux du samedi midi",
    description: "Votre taux d'occupation le samedi midi n'est que de 45%. Lancez une campagne marketing ciblée pour attirer plus de clients business.",
    impact: "high",
    effort: "medium",
    potentialGain: "+15% de réservations",
    status: "new",
  },
  {
    id: "rec-002",
    category: "reputation",
    title: "Répondre aux 8 avis en attente",
    description: "Les avis sans réponse depuis plus de 48h impactent négativement votre score de réactivité. Prenez 15 minutes pour y répondre.",
    impact: "high",
    effort: "low",
    potentialGain: "+0.2 sur la note moyenne",
    status: "urgent",
  },
  {
    id: "rec-003",
    category: "marketing",
    title: "Relancer les clients inactifs",
    description: "324 clients n'ont pas réservé depuis 3 mois. Une campagne de réactivation avec offre spéciale pourrait les faire revenir.",
    impact: "medium",
    effort: "low",
    potentialGain: "+45 réservations estimées",
    status: "suggested",
  },
  {
    id: "rec-004",
    category: "protection",
    title: "Activer la garantie CB pour les grands groupes",
    description: "Vos no-shows sur les réservations de 6+ personnes coûtent en moyenne 180€. Activez la garantie CB pour ces cas.",
    impact: "high",
    effort: "low",
    potentialGain: "Récupération de 90% des pertes",
    status: "suggested",
  },
];

// Mode démo activé globalement
export const DEMO_MODE = true;
